[project]
name = "hytale-modding-internal-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiomysql>=0.3.2",
    "fastapi>=0.124.4",
    "uvicorn>=0.38.0",
]
